# Generated by Django 3.1.4 on 2021-12-16 13:48

import api.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('first_name', models.CharField(db_column='first name', max_length=50, null=True)),
                ('last_name', models.CharField(db_column='last name', max_length=50, null=True)),
                ('mobile', models.CharField(max_length=15, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'User',
            },
            managers=[
                ('objects', api.user.models.CustomUserManager()),
            ],
        ),
    ]
